<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Wocel.Capture.Core/Wocel.Capture.Core.csproj" />
    <ProjectReference Include="../Wocel.Capture.Platform/Wocel.Capture.Platform.csproj" />
    <ProjectReference Include="../Wocel.Capture.Platform.Windows/Wocel.Capture.Platform.Windows.csproj" />
    <ProjectReference Include="../Wocel.Capture.Rendering/Wocel.Capture.Rendering.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>
</Project>
