<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Wocel.Capture.Platform</RootNamespace>
    <AssemblyName>Wocel.Capture.Platform</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Wocel.Capture.Core/Wocel.Capture.Core.csproj" />
  </ItemGroup>
</Project>
